spring:
  data:
    mongodb:
      uri: mongodb+srv://InventoTrack:M%40nsi1234@cluster0.6emwr5g.mongodb.net/order-service-db?retryWrites=true&w=majority

server:
  port: 9090

logging:
  level:
    org:
      hibernate:
        type: trace
        stat: debug