spring:
  data:
    mongodb:
      uri: mongodb+srv://Mansi:M%40nsi1234@cluster0.6emwr5g.mongodb.net/order-service-db?retryWrites=true&w=majority

server:
  port: 9090

logging:
  level:
    org:
      hibernate:
        type: trace
        stat: debug
sendgrid:
  api:
    key: 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
  from:
    email: dhruvajyotipramanik123@gmail.com

jwt:
  secret: 8frReDs1KJC8xWBkSExXUfjlBPldUzRX6J5X7V/EivZn7GLltqp+aUWwyjaR2tnhA8ussKwFrVVhsywErw6dyg==
  expiration: 3600000