spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springjdbc?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a5@2K414*
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
  logging:
    level:
      org:
        hibernate:
          type: trace
          stat: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: 8frReDs1KJC8xWBkSExXUfjlBPldUzRX6J5X7V/EivZn7GLltqp+aUWwyjaR2tnhA8ussKwFrVVhsywErw6dyg==
  expiration: 3600000